### ISSUE TITLE
User feedback notes on 'Visualising data on the web with Python and Dash' 

### ISSUE THREAD

**Issue by Joalewis** [researchdata-sheffield/dataviz-hub#20]
User feedback notes on 'Visualising data on the web with Python and Dash' http://dataviz.shef.ac.uk/tutorials/dash/

1. Installation: What interface is used to input the 'pip install' code?

3. First step: Where is this code to be inputted and how is this executed?
	Do we write a python file, app.py, containing this?

4. Download and read a CSV file: Add this line to the app.py file?

5. Preview dataset: How to run this to display the table?

6. Layout: Add this to app.py to format layout

7. Interactivity: Add this to app.py to create graph.

8. Style: Add to app.py file

9. Running application: Add to app.py to execute code. Run code by entering in iPython 	or anaconda interface: 
	>python app.py

10. Related technologies: How do we find other graphs / plots / visualisations to display the 	same data?

	How do we use this visualisation with other datasets?

**Comment by jezcope** [comment]
Thanks @Joalewis. I think the main changes we need then are:

- [ ] Specify what the expected prior knowledge is
- [ ] Make it clear which code is to be added to `app.py`
