### ISSUE TITLE
Add instructions for adding a new page

### ISSUE THREAD

**Issue by annakrystalli** [researchdata-sheffield/dataviz-hub#4]
## New markdown
- new page by creating new file in **`pages/`** dir.
## New rmarkdown
- if `.rmd`, create in **`rmd/`** and render to the  **`pages/`** dir.
## New jupyter notebook
- if an `.ipnb`
  - in the .ipnb, go to **`edit`**,  then **`edit notebook metadata`** and add the following snippet to the top level of the **notebook metadata.json**
    ```
    "nikola": {
        "title": "Visualising Networks",
        "slug": "visualising-networks",
        "date": "2012-09-15 19:52:05 UTC"
    }
    ```

**Comment by jezcope** [comment]
Also need to mention adding metadata to markdown files. We'll need to double-check that any YAML metadata is preserved in the `.rmd` → `.md` conversion.

**Comment by annakrystalli** [comment]
Agreed! Will test behaviour.

**Comment by annakrystalli** [comment]
In fact maybe we need a metadata check testing suite for all the different file types?

**Comment by jezcope** [comment]
I think any problems should get caught by the compilation check that Travis is now doing.

**Comment by annakrystalli** [comment]
OK sweet! Maybe just make sure what's required is clear in the documentation.  Will close this now then.
